[package]
name = "stardust-xr-gravity"
version = "0.1.1"
edition = "2021"
description = "Utility to launch apps and stardust clients spatially"
authors = ["Nova King <technobaboo@proton.me>"]
license = "MIT"
repository = "https://github.com/StardustXR/gravity"

[[bin]]
name = "gravity"
path = "src/main.rs"

[dependencies]
tokio = { version = "1.21.1", features = ["full"] }
glam = { version = "0.21.3", features = ["mint"] }
mint = "0.5.9"
clap = { version = "3.2.22", features = ["derive"] }
nix = { version = "0.25.0", default-features = false, features = ["process"] }
ustr = "0.9.0"
stardust-xr-fusion = "0.14.1"
